### ISSUE TITLE
attempt to index local 'thumbnailCoords' (a nil value)

### ISSUE THREAD

**Issue by xopez** [ksprugevics/rafs-mapvote#34] opened 2023-11-24 16:21 UTC
Sometimes users get following error:
```
[ERROR] lua/client/vgui/rmv_mapvote_panel.lua:466: attempt to index local 'thumbnailCoords' (a nil value)
  1. initAvatarBounce - lua/client/vgui/rmv_mapvote_panel.lua:466
   2. RMVRefreshAvatars - lua/client/vgui/rmv_mapvote_panel.lua:514
    3. func - lua/client/rmv_cl_rafsmapvote.lua:45
     4. unknown - lua/includes/extensions/net.lua:38
```

**Comment by ksprugevics** [comment] 2023-11-27 13:24
Known bug and a duplicate of [this issue](https://github.com/ksprugevics/rafs-mapvote/issues/30). Unfortunately, this project has went on the backburner a little bit..

**Closed** 2024-01-01 13:01 UTC
Labels: bug
